name       : webapp-manager
version    : 1.4.0
release    : 1
source     :
    - http://packages.linuxmint.com/pool/main/w/webapp-manager/webapp-manager_1.4.0_all.deb : be20eb22660c28d2527b9925e1edbc1baad150c8a19a182b679f19c0dd85685b
license    : GPL-3.0-or-later
component  : system.utils
extract	   : false
summary    : Web app manager from Linux Mint.
description: |
    Web app manager from Linux Mint.
rundeps    :
    - python-setproctitle
    - python-pillow
    - python-beautifulsoup4
    - python-unidecode
    - pip
    - xapp
setup    : |
    # 1. Creamos un directorio temporal para extraer el contenido del deb
    # 2. Extraemos los componentes del .deb (ar suele estar en el path de construcción)
    ar x $sources/webapp-manager_1.4.0_all.deb
    # 3. Extraemos el data.tar.xz dentro de nuestra carpeta temporal
    tar xf data.tar.*
install    : |
    # 4. Ahora movemos TODO el contenido de 'extra' a $installroot
    # Esto asegura que ypkg vea los archivos dentro de la "falsa raíz"
    mkdir -p $installdir
    cp -r usr $installdir/
