name       : i965-va-driver-shaders
version    : 2.4.1
release    : 3
source     :
    - http://deb.debian.org/debian/pool/non-free/i/intel-vaapi-driver-shaders/intel-vaapi-driver-shaders_2.4.1.orig.tar.gz : 03cd7e16acc94f828b6e7f3087863d8ca06e99ffa3385588005b1984bdd56157
license    : GPL-3.0-or-later
component  : system.utils
extract	   : true
summary    : VAAPI driver for Intel G45 & HD Graphics family.
description: |
    The VA-API (Video Acceleration API) enables hardware accelerated video decode/encode at various entry-points (VLD, IDCT, Motion Compensation etc.) for the prevailing coding standards today (MPEG-2, MPEG-4 ASP/H.263, MPEG-4 AVC/H.264, and VC-1/WMV3). It provides an interface to fully expose the video decode capabilities in today's GPUs.
rundeps    :
    - libva
patches    :
    - A0001-fix-exporting-buffers-with-3-planes.patch
    - 0002-Make-wl_drm-optional.patch
setup      : |    
setup    : |
    # 1. Creamos un directorio temporal para extraer el contenido del deb
    # 2. Extraemos los componentes del .deb (ar suele estar en el path de construcción)
    #ar x $sources/i965-va-driver-shaders_2.4.1-2_amd64.deb
    # 3. Extraemos el data.tar.xz dentro de nuestra carpeta temporal
    #cd intel-vaapi-driver-2.4.1
    
    patch -p1 < $pkgfiles/0001-fix-exporting-buffers-with-3-planes.patch
    patch -p1 < $pkgfiles/0002-Make-wl_drm-optional.patch
    
    %meson_configure
build      : |
    %ninja_build
install    : |
    # 4. Ahora movemos TODO el contenido de 'extra' a $installroot
    # Esto asegura que ypkg vea los archivos dentro de la "falsa raíz"
    %ninja_install
